/*
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.engie.csai.pc.core.model.json;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.Valid;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * PDTs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2021-11-30T12:38:51.556Z")
public class CategoriesConfigJson
{
  @JsonProperty("networkConfig")
  private List<CategoryConfigJson> networkConfigs = null;

  public CategoriesConfigJson networkConfig(List<CategoryConfigJson> networkConfigs) {
    this.networkConfigs = networkConfigs;
    return this;
  }

  public CategoriesConfigJson addNetworkConfig(CategoryConfigJson categoryConfigJson) {
    if (this.networkConfigs == null) {
      this.networkConfigs = new ArrayList<CategoryConfigJson>();
    }
    this.networkConfigs.add(categoryConfigJson);
    return this;
  }

  /**
   * Get pdts
   * @return pdts
   **/
  @JsonProperty("networkConfig")
  @ApiModelProperty(value = "")
  @Valid
  public List<CategoryConfigJson> getNetworkConfigs() {
    return networkConfigs;
  }

  public void setNetworkConfigs(List<CategoryConfigJson> networkConfigs) {
    this.networkConfigs = networkConfigs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoriesConfigJson clientRequestsJson = (CategoriesConfigJson) o;
    return Objects.equals(this.networkConfigs, clientRequestsJson.networkConfigs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(networkConfigs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoriesConfigJson {\n");
    
    sb.append("    networkConfigs: ").append(toIndentedString(networkConfigs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

