/*
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.engie.csai.pc.core.model.json;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * PDT
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2021-11-30T12:38:51.556Z")
public class CategoryConfigJson
{
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("numberOfQuota")
  private Integer numberOfQuota = null;

  @JsonProperty("numberOfInitialTokens")
  private Integer numberOfInitialTokens = null;

  @JsonProperty("numberOfRequests")
  private Integer numberOfRequests = null;

  @JsonProperty("capacity")
  private Integer capacity = null;

  @JsonProperty("pql")
  private Integer pql = null;

  @JsonProperty("maxDataSize")
  private Integer maxDataSize = null;

  @JsonProperty("numberOfClients")
  private Integer numberOfClients = null;

  public CategoryConfigJson name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CategoryConfigJson numberOfQuota(Integer numberOfQuota) {
    this.numberOfQuota = numberOfQuota;
    return this;
  }

  /**
   * Get senderSignature
   * @return senderSignature
   **/
  @JsonProperty("numberOfQuota")
  @ApiModelProperty(value = "")
  public Integer getNumberOfQuota() {
    return numberOfQuota;
  }

  public void setNumberOfQuota(Integer numberOfQuota) {
    this.numberOfQuota = numberOfQuota;
  }

  @JsonProperty("numberOfClients")
  @ApiModelProperty(value = "")
  public Integer getNumberOfClients() {
    return numberOfClients;
  }

  public void setNumberOfClients(Integer numberOfClients) {
    this.numberOfClients = numberOfClients;
  }

  public CategoryConfigJson numberOfInitialTokens(Integer numberOfInitialTokens) {
    this.numberOfInitialTokens = numberOfInitialTokens;
    return this;
  }

  /**
   * Get validityStatus
   * @return validityStatus
   **/
  @JsonProperty("numberOfInitialTokens")
  @ApiModelProperty(value = "")
  public Integer getNumberOfInitialTokens() {
    return numberOfInitialTokens;
  }

  public void setNumberOfInitialTokens(Integer numberOfInitialTokens) {
    this.numberOfInitialTokens = numberOfInitialTokens;
  }

  public CategoryConfigJson numberOfRequests(Integer numberOfRequests) {
    this.numberOfRequests = numberOfRequests;
    return this;
  }

  /**
   * Get validityStatus
   * @return validityStatus
   **/
  @JsonProperty("numberOfRequests")
  @ApiModelProperty(value = "")
  public Integer getNumberOfRequests() {
    return numberOfRequests;
  }

  public void setNumberOfRequests(Integer numberOfRequests) {
    this.numberOfRequests = numberOfRequests;
  }

  public CategoryConfigJson capacity(Integer capacity) {
    this.capacity = capacity;
    return this;
  }

  /**
   * Get fee
   * @return fee
   **/
  @JsonProperty("capacity")
  @ApiModelProperty(value = "")
  public Integer getCapacity() {
    return capacity;
  }

  public void setcapacity(Integer capacity) {
    this.capacity = capacity;
  }

  @JsonProperty("maxDataSize")
  @ApiModelProperty(value = "")
  public Integer getMaxDataSize() {
    return maxDataSize;
  }

  public void setMaxDataSize(Integer maxDataSize) {
    this.maxDataSize = maxDataSize;
  }

  public CategoryConfigJson data(Integer pql) {
    this.pql = pql;
    return this;
  }

  /**
   * Get data
   * @return data
   **/
  @JsonProperty("pql")
  @ApiModelProperty(value = "")
  public Integer getPql() {
    return pql;
  }

  public void setPql(Integer pql) {
    this.pql = pql;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryConfigJson ClientRequestJson = (CategoryConfigJson) o;
    return Objects.equals(this.name, ClientRequestJson.name) &&
        Objects.equals(this.numberOfQuota, ClientRequestJson.numberOfQuota) &&
        Objects.equals(this.numberOfInitialTokens, ClientRequestJson.numberOfInitialTokens) &&
        Objects.equals(this.numberOfRequests, ClientRequestJson.numberOfRequests) &&
        Objects.equals(this.capacity, ClientRequestJson.capacity) &&
        Objects.equals(this.pql, ClientRequestJson.pql);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, numberOfQuota, numberOfInitialTokens, numberOfRequests, capacity, pql);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PDT {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    numberOfQuota: ").append(toIndentedString(numberOfQuota)).append("\n");
    sb.append("    numberOfInitialTokens: ").append(toIndentedString(numberOfInitialTokens)).append("\n");
    sb.append("    numberOfRequests: ").append(toIndentedString(numberOfRequests)).append("\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("    pql: ").append(toIndentedString(pql)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

