/*
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.engie.csai.pc.core.model.json;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * PDT
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2021-11-30T12:38:51.556Z")public class ClientRequestJson {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("sender_signature")
  private String senderSignature = null;

  @JsonProperty("validity_status")
  private Boolean validityStatus = null;

  @JsonProperty("fee")
  private Float fee = null;

  @JsonProperty("data")
  private String data = null;

  @JsonProperty("tokenToSend")
  private Integer tokenToSend = null;

  @JsonProperty("receiver_address")
  private String receiverAddress = null;

  public ClientRequestJson name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ClientRequestJson senderSignature(String senderSignature) {
    this.senderSignature = senderSignature;
    return this;
  }

  /**
   * Get senderSignature
   * @return senderSignature
   **/
  @JsonProperty("sender_signature")
  @ApiModelProperty(value = "")
  public String getSenderSignature() {
    return senderSignature;
  }

  public void setSenderSignature(String senderSignature) {
    this.senderSignature = senderSignature;
  }

  public ClientRequestJson validityStatus(Boolean validityStatus) {
    this.validityStatus = validityStatus;
    return this;
  }

  /**
   * Get validityStatus
   * @return validityStatus
   **/
  @JsonProperty("validity_status")
  @ApiModelProperty(value = "")
  public Boolean isValidityStatus() {
    return validityStatus;
  }

  public void setValidityStatus(Boolean validityStatus) {
    this.validityStatus = validityStatus;
  }

  public ClientRequestJson fee(Float fee) {
    this.fee = fee;
    return this;
  }

  /**
   * Get fee
   * @return fee
   **/
  @JsonProperty("fee")
  @ApiModelProperty(value = "")
  public Float getFee() {
    return fee;
  }

  public void setFee(Float fee) {
    this.fee = fee;
  }

  public ClientRequestJson data(String data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   **/
  @JsonProperty("data")
  @ApiModelProperty(value = "")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }

  public ClientRequestJson tokenToSend(Integer tokenToSend) {
    this.tokenToSend = tokenToSend;
    return this;
  }

  /**
   * Get tokenToSend
   * @return tokenToSend
   **/
  @JsonProperty("tokenToSend")
  @ApiModelProperty(value = "")
  public Integer getTokenToSend() {
    return tokenToSend;
  }

  public void setTokenToSend(Integer tokenToSend) {
    this.tokenToSend = tokenToSend;
  }

  public ClientRequestJson receiverAddress(String receiverAddress) {
    this.receiverAddress = receiverAddress;
    return this;
  }

  /**
   * Get receiverAddress
   * @return receiverAddress
   **/
  @JsonProperty("receiver_address")
  @ApiModelProperty(value = "")
  public String getReceiverAddress() {
    return receiverAddress;
  }

  public void setReceiverAddress(String receiverAddress) {
    this.receiverAddress = receiverAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientRequestJson ClientRequestJson = (ClientRequestJson) o;
    return Objects.equals(this.name, ClientRequestJson.name) &&
        Objects.equals(this.senderSignature, ClientRequestJson.senderSignature) &&
        Objects.equals(this.validityStatus, ClientRequestJson.validityStatus) &&
        Objects.equals(this.fee, ClientRequestJson.fee) &&
        Objects.equals(this.data, ClientRequestJson.data) &&
        Objects.equals(this.tokenToSend, ClientRequestJson.tokenToSend) &&
        Objects.equals(this.receiverAddress, ClientRequestJson.receiverAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, senderSignature, validityStatus, fee, data, tokenToSend, receiverAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PDT {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    senderSignature: ").append(toIndentedString(senderSignature)).append("\n");
    sb.append("    validityStatus: ").append(toIndentedString(validityStatus)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    tokenToSend: ").append(toIndentedString(tokenToSend)).append("\n");
    sb.append("    receiverAddress: ").append(toIndentedString(receiverAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

