version: '3.8'

services:
  pc:
    container_name: pc
    build: .
    networks:
      - default
    links:
      - "rabbitmq:rabbitmq"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672