/*
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.engie.csai.pc.model.json;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.Valid;

/**
 * PDTs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2021-11-30T12:38:51.556Z")public class ClientRequestsJson {
  @JsonProperty("pdts")
  private List<ClientRequestJson> ClientRequestJsons = null;

  public ClientRequestsJson pdts(List<ClientRequestJson> ClientRequestJsons) {
    this.ClientRequestJsons = ClientRequestJsons;
    return this;
  }

  public ClientRequestsJson addRequestsItem(ClientRequestJson pdtsItem) {
    if (this.ClientRequestJsons == null) {
      this.ClientRequestJsons = new ArrayList<ClientRequestJson>();
    }
    this.ClientRequestJsons.add(pdtsItem);
    return this;
  }

  /**
   * Get pdts
   * @return pdts
   **/
  @JsonProperty("pdts")
  @ApiModelProperty(value = "")
  @Valid
  public List<ClientRequestJson> getRequests() {
    return ClientRequestJsons;
  }

  public void setPdts(List<ClientRequestJson> ClientRequestJsons) {
    this.ClientRequestJsons = ClientRequestJsons;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientRequestsJson clientRequestsJson = (ClientRequestsJson) o;
    return Objects.equals(this.ClientRequestJsons, clientRequestsJson.ClientRequestJsons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ClientRequestJsons);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PDTs {\n");
    
    sb.append("    pdts: ").append(toIndentedString(ClientRequestJsons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

